- name: Install Kubectl
  hosts: localhost
  tasks:
    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present

    - name: Install Kubectl using snap
      community.general.snap:
        name: kubectl
        state: present
        classic: true

