- name: Install Kubectl
  hosts: localhost
  user: ubuntu
  become: true

  tasks:
    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present

    - name: Install Kubectl using snap
      community.general.snap:
        name: kubectl
        state: present
        classic: true

- name: Install Minikube
  hosts: localhost
  user: ubuntu
  become: true

  tasks:
    - name: Download Minikube binary
      ansible.builtin.command:
        cmd: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

    - name: Install Minikube
      ansible.builtin.command:
        cmd: install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Remove Minikube binary
      ansible.builtin.file:
        path: minikube-linux-amd64
        state: absent