- name: Delete Deployment
  hosts: localhost
  user: ubuntu

  tasks:
    - name: Delete Deployment
      ansible.builtin.command:
        cmd: kubectl delete deploy/cw2-server

- name: Delete MiniKube
  hosts: localhost
  user: ubuntu

  tasks:
    - name: Delete MiniKube
      ansible.builtin.command:
        cmd: minikube delete

- name: Install Kubectl
  hosts: localhost
  user: ubuntu
  become: true

  tasks:
    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present

    - name: Install Kubectl using snap
      community.general.snap:
        name: kubectl
        state: present
        classic: true

- name: Install Minikube
  hosts: localhost
  user: ubuntu
  become: true

  tasks:
    - name: Download Minikube binary
      ansible.builtin.command:
        cmd: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

    - name: Install Minikube
      ansible.builtin.command:
        cmd: install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Remove Minikube binary
      ansible.builtin.file:
        path: minikube-linux-amd64
        state: absent

- name: Start Minikube
  hosts: localhost
  user: ubuntu
  #  become: true

  tasks:
    - name: Start Minikube
      ansible.builtin.command:
        cmd: minikube start

- name: Deploy image from Dockerhub to Kubernetes
  hosts: localhost
  user: ubuntu
  #  become: true

  tasks:
    - name: Download image from Dockerhub
      ansible.builtin.command:
        cmd: kubectl create deployment cw2-server --image=kymmie/cw2-server:1.0

    - name: Create a NodePort service
      ansible.builtin.command:
        cmd: kubectl expose deployment/cw2-server --type="NodePort" --port 8080 --name node-port-service

    - name: Scale the deployment
      ansible.builtin.command:
        cmd: kubectl scale deployment/cw2-server --replicas=3