- name: Delete Deployment
  hosts: localhost
  user: ubuntu

  tasks:
    - name: Delete Deployment
      ansible.builtin.command:
        cmd: kubectl delete deploy/cw2-server

- name: Delete MiniKube
  hosts: localhost
  user: ubuntu

  tasks:
    - name: Delete MiniKube
      ansible.builtin.command:
        cmd: minikube delete

